### ISSUE TITLE
Road Map

### ISSUE THREAD

**Issue by mildronize** [TechNukrom/data-crawler#3]
ตอนนี้ที่ทำได้แล้ว
- [X] get item = link + content + author + tag  + other
- [X] make a hash key from link, content
- [X] write  to db if no exist key ( protect duplicate item)
- [X] ให้ run script ทุกสัปดาห์ โดย travis.ci

แผนต่อไป:
- [ ] รองรับ source ที่หลากหลายเว็บมากขึ้น
- [ ] อาจจะใช้ [https://scrapy.org/](https://scrapy.org/) ในการดึง data แทน feed

ปรับปรุง
- [ ] แยก branch dev , กับ production
